linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disable:
    - gochecknoinits
    - gochecknoglobals

run:
  tests: true
